
import Providers from './Providers'
import './globals.css'
import { Inter } from 'next/font/google'

import {LoadContextProvider} from './state/Context'
import { Toaster } from 'react-hot-toast'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
  <Toaster />
        <Providers>
          <LoadContextProvider>
             {children}
         </LoadContextProvider>
      
           
         
          </Providers>
        </body>
    </html>
  )
}
